/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Form: typeof import('./../components/Avatar/Form.vue')['default']
    Result: typeof import('./../components/Avatar/Result.vue')['default']
    TabSwitcher: typeof import('./../components/Ui/TabSwitcher.vue')['default']
    Variants: typeof import('./../components/Ui/Variants.vue')['default']
  }
}
